[package]
name = "pyth"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.11.1"
openzeppelin = "1.0.0"

[dev-dependencies]
snforge_std = "0.38.3"

[lib]

[[target.starknet-contract]]
build-external-contracts = ["openzeppelin::presets::erc20::ERC20Upgradeable"]
